apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: indocyber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tiosetiaatih/hello-world:latest
        ports:
        - containerPort: 8080